--------------------------------------------------------
--  DDL for Trigger AUTHORS_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "COS_457_FINAL"."AUTHORS_TRG" 
BEFORE INSERT ON AUTHORS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.AUTHORID IS NULL THEN
      SELECT AUTHORS_SEQ.NEXTVAL INTO :NEW.AUTHORID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "COS_457_FINAL"."AUTHORS_TRG" ENABLE;
